Rename params and env variables to make them consistent
Pure-Storage-Ansible/Fusion-Collection pull request #121
Opened 2023-04-25 13:40 UTC by andreepyro

##### SUMMARY
Rename params and env variables to make them consistent

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- fusion_api_client
- fusion_array
- fusion_az
- fusion_hap
- fusion_info
- fusion_ni
- fusion_nig
- fusion_pg
- fusion_pp
- fusion_ra
- fusion_region
- fusion_sc
- fusion_se
- fusion_ss
- fusion_tenant
- fusion_ts
 - fusion_volume

2023-04-25 14:29 UTC, sdodsley requested changes
You can't just change these without giving a deprecation period for the existing variables. 
You should add support for the new variables, fully document the change and run them in parallel with the existing variables.
They can then be removed at a designated point in the future, say 2 collection y-releases.

You can change the playbook examples though - they don't need both. Just the core code

2023-04-25 15:02 UTC, jankodera-ps commented
`plugins/module_utils/fusion.py` needs to handle both. I would say read new ENV variables, if not present, try to read the old ones?

2023-04-26 08:39 UTC, jankodera-ps submitted a review, later dismissed

2023-04-26 08:47 UTC, andreepyro commented
Everything fixed. All env variables and parameters properly deprecated.

Please review @sdodsley

2023-04-26 08:57 UTC, jankodera-ps approved these changes

2023-04-26 09:45 UTC, dimleevik approved these changes

2023-04-26 13:15 UTC, sdodsley approved these changes

2023-04-26 14:12 UTC, merged