updated base path for ansible
Pure-Storage-Ansible/Fusion-Collection pull request #127
Opened 2023-04-28 15:56 UTC by dimleevik

##### SUMMARY

Updated base path for ansible collection

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins

2023-04-28 17:09 UTC, sdodsley submitted a review, later dismissed

2023-04-28 18:21 UTC, vromash commented on plugins/module_utils/fusion.py
> +    if ENV_API_HOST in environ:
why `ENV_HOST` was removed? it should be in use until we deprecate it in 2.0.0

2023-04-29 06:01 UTC, andreepyro requested changes
Please leave ENV_HOST variable in place.

2023-05-02 08:23 UTC, jankodera-ps approved these changes

2023-05-02 13:05 UTC, vromash submitted a review, later dismissed

2023-05-02 13:06 UTC, vromash commented
don't we need changelog for that?

2023-05-02 14:45 UTC, sdodsley approved these changes

2023-05-02 15:49 UTC, DenDen039 commented on changelogs/127_change_logic_of_fusion_api_host.yml
> +  - FUSION_API_HOST && FUSION_HOST - changed logic, now this variables require host name without path
Or we just need to document somewhere that you can specify Fusion host parameter. As well as tex field

2023-05-03 08:28 UTC, jankodera-ps approved these changes

2023-05-03 09:03 UTC, DenDen039 approved these changes

2023-05-03 09:05 UTC, jankodera-ps commented
@andreepyro Were the requested changes met?

2023-05-03 09:08 UTC, andreepyro approved these changes

2023-05-03 09:10 UTC, andreepyro commented
> @andreepyro Were the requested changes met?

@dimleevik @jankodera-ps Sorry, didn't notice the new commits. Yes, look good to me now :)

2023-05-04 08:33 UTC, merged