fusion_info: show warning on status #403 ApiException, otherwise use …
Pure-Storage-Ansible/Fusion-Collection pull request #84
Opened 2023-02-21 13:16 UTC by andreepyro

##### SUMMARY
This change introduces the following behaviour for module_fusion:
- if status #403 exception occurs, permission denied warning will be printed, but fusion_info module will return rest of the requested data
- if `purefusion.rest.ApiException` or `OperationException` occurs, it will be handled by error hook already used in toher modules
- code refactor: mainly changing `collection.items[ind] for ind in range(0, len(collection.items)):` pattern to `element for element in collection.items` (does the same but it is a lot easier to read)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/fusion_info.py

2023-02-21 13:17 UTC, andreepyro commented
Please don't merge until it's reviewed by the Pure Storage Fusion team

2023-02-28 11:29 UTC, genalt commented on plugins/modules/fusion_info.py
> +                if exc.status == 403:
If it's not a permission denied, we should rethrow the exception, which will be handled a layer above

2023-02-28 11:31 UTC, genalt commented on plugins/modules/fusion_info.py
> +        if exc.status == 403:
Please use a code from [http](https://docs.python.org/3/library/http.html#module-http)
In other places as well.

2023-02-28 11:32 UTC, genalt requested changes
Looks good. Just add several minor fixes. Thanks!

2023-03-01 12:44 UTC, genalt requested changes
There is a problem during testing:
```
fusion_info.py\", line 976, in generate_volumes_dict\nAttributeError: 'NoneType' object has no attribute 'name'\n"
```

2023-03-01 15:37 UTC, andreepyro commented
@genalt Thanks for noticing!

2023-03-02 08:10 UTC, genalt requested changes
There is one bug, please fix it.

Also, we have a bunch of warnings:
```
[WARNING]: Cannot get Hardware Types in [default dict], reason: Permission denied
[WARNING]: Cannot get Appliances in [default dict], reason: Permission denied
[WARNING]: Cannot get Network Interface Groups in [default dict], reason: Permission denied
[WARNING]: Cannot get Network Interfaces in [default dict], reason: Permission denied
[WARNING]: Cannot get [hardware dict], reason: Permission denied
[WARNING]: Cannot get [interfaces dict], reason: Permission denied
[WARNING]: Cannot get [arrays dict], reason: Permission denied
[WARNING]: Cannot get [network_interface_groups dict], reason: Permission denied
```
I see there are duplicates, but just with a different format. It looks like the exception was handled in a particular method that generates a single default dict (using decorator), but then you handle it again

2023-03-02 08:10 UTC, genalt commented on plugins/modules/fusion_info.py
> +                                nig.name for nig in iface.network_interface_groups
there is a problem:
`fusion_info.py\", line 855, in generate_se_dict\nTypeError: 'NoneType' object is not iterable\n`

I would suggest just to add something like `nig.name for nig in (iface.network_interface_groups or [])`

2023-03-02 12:43 UTC, genalt approved these changes

2023-03-02 15:28 UTC, merged